/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: daa8f43b3b3c829734c537405d5aca30)
interface __BaseEnv_Env {
	DB: D1Database;
	SITE_NAME: "Waline";
	DISABLE_USER_AGENT: "false";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_NAME" | "DISABLE_USER_AGENT">> {}
}
